ALTER TABLE users ADD COLUMN otp VARCHAR(10) NULL;
ALTER TABLE users ADD COLUMN otp_expires TIMESTAMP NULL;

ALTER TABLE doctors ADD COLUMN otp VARCHAR(10) NULL;
ALTER TABLE doctors ADD COLUMN otp_expires TIMESTAMP NULL;
